---
classifications:
  http://identifier.buildingsmart.org/uri/buildingsmart/ifc-4.3: false
  http://identifier.buildingsmart.org/uri/pdt/pdt-1.0: false
  http://identifier.buildingsmart.org/uri/nlsfb/nlsfb2005-2.2: false
  http://identifier.buildingsmart.org/uri/promaterial/universaltypes-1.0: false
  http://identifier.buildingsmart.org/uri/gsa/gsaspace-23: false
  http://identifier.buildingsmart.org/uri/sbe/swedishmaterials-1: false
  http://identifier.buildingsmart.org/uri/nbs/uniclass2015-1: false
  http://identifier.buildingsmart.org/uri/csi/omniclass-1: false
  http://identifier.buildingsmart.org/uri/planbim/planbim-1: false
  http://identifier.buildingsmart.org/uri/efalbhm/arge-0.1: false
  http://identifier.buildingsmart.org/uri/molio/cciconstruction-1.0: false
  http://identifier.buildingsmart.org/uri/dtc/dtdl-1: false
  http://identifier.buildingsmart.org/uri/bimlib/bimlib-ru-temp-1: false
  http://identifier.buildingsmart.org/uri/fvhf/vhf-0.002: false
  http://identifier.buildingsmart.org/uri/buildingsmart-fr/BRIDGE-MINnD-1.0: false
  http://otl.amsterdam.nl: false
  http://identifier.buildingsmart.org/uri/jacic/jacic-0.0: false
  http://identifier.buildingsmart.org/uri/jacic/jacic-1.0: false
  http://identifier.buildingsmart.org/uri/jacic/jacic-1.1: false
  http://rdf.vegdata.no/V440/v440-owl: false
  http://identifier.buildingsmart.org/uri/buildingsmart-de/bsdbp-1: false
  http://identifier.buildingsmart.org/uri/buildingsmart-fr/MINnD-1.0: false
  http://identifier.buildingsmart.org/uri/buildingsmart-ch/UCM-CH-Demo-1.0: false
  http://identifier.buildingsmart.org/uri/buildingsmart/demo-2-1.0: false
  http://identifier.buildingsmart.org/uri/growingcircle/transsmart-0.1: false
  http://identifier.buildingsmart.org/uri/ifcrail/ifcrail-0.1: false
  http://identifier.buildingsmart.org/uri/bimeta/bimeta-0.1: false
  http://identifier.buildingsmart.org/uri/ifcrail/ifcrail-1.0: false
  http://identifier.buildingsmart.org/uri/VDMAPumpsSystems/VDMAPumpsSystems-0.1: false
  http://identifier.buildingsmart.org/uri/MTR/MTR-1: false
  http://identifier.buildingsmart.org/uri/bimdata/bimdata-1.0: false
  http://identifier.buildingsmart.org/uri/buildingsmart/demo-2-1.1: false
  http://identifier.buildingsmart.org/uri/buildingsmart-fr/MINnD-Pavement-1.0: false
  http://identifier.buildingsmart.org/uri/buildingsmart-fr/MINnD-Tunnel-1.0: false
  http://identifier.buildingsmart.org/uri/certi/ogsub-0.1: false
  http://identifier.buildingsmart.org/uri/FTIA/FTIA-1.0: false
  http://identifier.buildingsmart.org/uri/buildingsmart/bSDD-DEMO-mat-1.0: false
  http://identifier.buildingsmart.org/uri/ATALANE/REX-OBJ-1.0: false
  http://identifier.buildingsmart.org/uri/bimloket/naakt-0.1: false
  http://identifier.buildingsmart.org/uri/acca/ACCAtest-0.1: false
  http://identifier.buildingsmart.org/uri/buildingsmart-fr/MINnD-Earthwork-1.0: false
  http://identifier.buildingsmart.org/uri/digibase/volkerwesselsbv-0.1: false
  http://identifier.buildingsmart.org/uri/ArcDox/ArcDox-1.0: false
  http://identifier.buildingsmart.org/uri/BBRI/BBRI-0.1: false
  http://identifier.buildingsmart.org/uri/bimeta/bimeta-1.0: false
  http://identifier.buildingsmart.org/uri/BBRI/CCTB-2020: false
  http://identifier.buildingsmart.org/uri/ethz/hosszu-0.1: false
  http://identifier.buildingsmart.org/uri/mssk/mssk-0.1: false
  http://identifier.buildingsmart.org/uri/LCA/LCA-1.0: false
  http://identifier.buildingsmart.org/uri/BBRI/VMSW-2020: false
  http://identifier.buildingsmart.org/uri/BBRI/VMSW-2015: false
  http://identifier.buildingsmart.org/uri/dreso/din276plus-1.0: false
  http://identifier.buildingsmart.org/uri/ifcairport/ifcairport-1.0: false
  http://identifier.buildingsmart.org/uri/digibase/digibasebouwlagen-0.1: false
  http://identifier.buildingsmart.org/uri/digibase/nen2699-0.1: false
  http://identifier.buildingsmart.org/uri/uniweimar/uniweimar-0.1: false
  http://identifier.buildingsmart.org/uri/acca/ACCAtest-0.2: false
  http://identifier.buildingsmart.org/uri/acca/ACCAtest-0.21: false
  http://identifier.buildingsmart.org/uri/acca/ACCAtest-0.22: false
  http://identifier.buildingsmart.org/uri/acca/ACCAtest-0.24: false
  http://identifier.buildingsmart.org/uri/acca/ACCAtest-0.25: false
  http://identifier.buildingsmart.org/uri/acca/ACCAtest-0.26: false
  http://identifier.buildingsmart.org/uri/acca/ACCAtest-0.27: false
  http://identifier.buildingsmart.org/uri/acca/ACCAtest-0.28: false
  http://identifier.buildingsmart.org/uri/acca/ACCAtest-0.29: false
  http://identifier.buildingsmart.org/uri/acca/ACCAtest-0.30: false
  http://identifier.buildingsmart.org/uri/acca/ACCAtest-0.34: false
  http://identifier.buildingsmart.org/uri/acca/ACCAtest-0.35: false
  http://identifier.buildingsmart.org/uri/buildingsmart/bSI-wd-0.1: false
  http://identifier.buildingsmart.org/uri/acca/ACCAtest-0.40: false
  http://identifier.buildingsmart.org/uri/acca/ACCAtest-0.41: false
  http://identifier.buildingsmart.org/uri/acca/ACCAtest-0.50: false
  http://identifier.buildingsmart.org/uri/engisis/RFI-01: false
  http://identifier.buildingsmart.org/uri/engisis/RFI-02: false
  http://identifier.buildingsmart.org/uri/acca/ACCAtest-8.0: false
  http://identifier.buildingsmart.org/uri/acca/ACCAtest-9.0: false
  http://identifier.buildingsmart.org/uri/acca/ACCAtest-1.0: false
  http://identifier.buildingsmart.org/uri/testorg/TEST-0.1: false
  http://identifier.buildingsmart.org/uri/bs-agri/fruitvegs-1.0: false
  http://identifier.buildingsmart.org/uri/SIUE/nbe-0.1: false
ifc_version: IFC 2x3
ifc_versions:
- IFC 2x3
- IFC 4
recursive: true
